version: '3'

services:

  web:
    extends:
      file: docker-compose.yml
      service: web
    volumes:
      - ./:/var/www/html
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf

  php:
    build: .
    volumes:
      - ./:/var/www/html
    networks:
      - champimap_network

networks:
  champimap_network:

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
