version: '3'

services:
  database:
    container_name: champimap_db
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: champimap
      # You should definitely change the password in production
      POSTGRES_PASSWORD: champimap
      POSTGRES_USER: champimap
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    networks:
      - champimap_network

  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - champimap_network

  php:
    build: .
    volumes:
      - ./:/var/www/html
    networks:
      - champimap_network

networks:
  champimap_network:

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
