on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_deploy:
    name: run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: connect
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}"
      - name: updating repository
        run: git checkout ${{ secrets.MAIN_BRANCH }} && git pull --rebase origin main
      - name: run migrations
        run: make enter_php && php bin/console doctrine:migration:migrate && exit
      - name: install assets
        run: make enter_php && yarn install && yarn build && exit
      - name: exiting ssh
        run: exit
      - name: cleanup
        run: rm -rf ~/.ssh
